env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module

plugins:
  - react

settings:
  react:
    version: detect

ignorePatterns:
  - build/
  - node_modules/
  - coverage/
